export enum GameErrorCode {
  INVALID_MOVE = "INVALID_MOVE",
  NOT_YOUR_TURN = "NOT_YOUR_TURN",
  GAME_NOT_FOUND = "GAME_NOT_FOUND",
  UNAUTHORIZED = "UNAUTHORIZED",
  GAME_OVER = "GAME_OVER",
  ALREADY_IN_GAME = "ALREADY_IN_GAME",
}
